import type { Sermon } from "./types";

/**
 * Demo sermon catalog. Audio files are local placeholders generated by macOS
 * `say` so the demo plays offline; swap `audioUrl` for permissioned, real
 * sermons (HLS or MP3) once the ingestion pipeline is wired up.
 */
export const SERMONS: Sermon[] = [
  {
    id: "s-001",
    slug: "the-wait-that-builds-you",
    title: "The Wait That Builds You",
    pastorId: "p-tomide",
    scripture: "Psalm 27:14",
    topic: "Patience",
    tags: ["patience", "waiting", "formation"],
    publishedAt: "2026-06-08T09:00:00Z",
    durationSec: 28 * 60 + 14,
    audioUrl: "/audio/demo-1.wav",
    summary:
      "Waiting is not wasted time. Pastor Tomide unpacks David's posture in Psalm 27 and the unseen architecture God is building in seasons of delay.",
    hue: 32,
    viewsThisWeek: 18420,
  },
  {
    id: "s-002",
    slug: "when-god-whispers",
    title: "When God Whispers",
    pastorId: "p-mara",
    scripture: "1 Kings 19:11-13",
    topic: "Hearing God",
    tags: ["discernment", "prayer", "listening"],
    publishedAt: "2026-06-07T11:30:00Z",
    durationSec: 34 * 60 + 51,
    audioUrl: "/audio/demo-2.wav",
    summary:
      "Elijah expected the earthquake. Mara invites us back to the quiet still voice and a more honest practice of listening.",
    hue: 220,
    viewsThisWeek: 14210,
  },
  {
    id: "s-003",
    slug: "wells-in-the-wilderness",
    title: "Wells in the Wilderness",
    pastorId: "p-eli",
    scripture: "Genesis 21:14-19",
    topic: "Provision",
    tags: ["provision", "wilderness", "hagar"],
    publishedAt: "2026-06-05T14:00:00Z",
    durationSec: 31 * 60 + 7,
    audioUrl: "/audio/demo-3.wav",
    summary:
      "Hagar's well was already there before she saw it. A message on the provision of God that precedes our awareness of it.",
    hue: 12,
    viewsThisWeek: 11308,
  },
  {
    id: "s-004",
    slug: "the-mathematics-of-grace",
    title: "The Mathematics of Grace",
    pastorId: "p-grace",
    scripture: "Matthew 18:21-35",
    topic: "Forgiveness",
    tags: ["forgiveness", "grace", "parables"],
    publishedAt: "2026-06-01T10:00:00Z",
    durationSec: 41 * 60 + 22,
    audioUrl: "/audio/demo-1.wav",
    summary:
      "Seventy times seven is not a ceiling — it is a horizon. Grace breaks the calculator we keep score on.",
    hue: 145,
    viewsThisWeek: 9842,
  },
  {
    id: "s-005",
    slug: "born-for-this-moment",
    title: "Born for This Moment",
    pastorId: "p-jonah",
    scripture: "Esther 4:13-14",
    topic: "Calling",
    tags: ["calling", "courage", "esther"],
    publishedAt: "2026-05-30T16:45:00Z",
    durationSec: 26 * 60 + 39,
    audioUrl: "/audio/demo-2.wav",
    summary:
      "Mordecai's question for Esther is the same question pressing on you today. A message on courage at the threshold.",
    hue: 280,
    viewsThisWeek: 8210,
  },
  {
    id: "s-006",
    slug: "rest-is-not-retreat",
    title: "Rest Is Not Retreat",
    pastorId: "p-tomide",
    scripture: "Mark 6:30-32",
    topic: "Sabbath",
    tags: ["sabbath", "rest", "rhythm"],
    publishedAt: "2026-05-25T09:00:00Z",
    durationSec: 22 * 60 + 8,
    audioUrl: "/audio/demo-3.wav",
    summary:
      "Jesus pulled the disciples away on purpose. A short, practical message on building a rhythm of sabbath rest.",
    hue: 32,
    viewsThisWeek: 7120,
  },
  {
    id: "s-007",
    slug: "faith-that-has-hands",
    title: "Faith That Has Hands",
    pastorId: "p-eli",
    scripture: "James 2:14-26",
    topic: "Discipleship",
    tags: ["faith", "works", "james"],
    publishedAt: "2026-05-22T14:00:00Z",
    durationSec: 38 * 60 + 5,
    audioUrl: "/audio/demo-1.wav",
    summary:
      "James will not let us divorce belief from behaviour. A blunt, hopeful word on what faith looks like when it goes to work.",
    hue: 12,
    viewsThisWeek: 6840,
  },
  {
    id: "s-008",
    slug: "after-the-amen",
    title: "After the Amen",
    pastorId: "p-mara",
    scripture: "Nehemiah 1:4-11",
    topic: "Prayer",
    tags: ["prayer", "action", "nehemiah"],
    publishedAt: "2026-05-18T11:30:00Z",
    durationSec: 29 * 60 + 47,
    audioUrl: "/audio/demo-2.wav",
    summary:
      "Nehemiah wept, prayed, fasted — and then he packed. What we do after the amen is part of the prayer.",
    hue: 220,
    viewsThisWeek: 5410,
  },
  {
    id: "s-009",
    slug: "light-in-the-doorway",
    title: "Light in the Doorway",
    pastorId: "p-grace",
    scripture: "Hebrews 13:1-3",
    topic: "Hospitality",
    tags: ["hospitality", "love", "strangers"],
    publishedAt: "2026-05-12T10:00:00Z",
    durationSec: 24 * 60 + 33,
    audioUrl: "/audio/demo-3.wav",
    summary:
      "The early church was famous for its doors. Grace makes the case that hospitality is still a frontline ministry.",
    hue: 145,
    viewsThisWeek: 4220,
  },
];

export function getSermonById(id: string): Sermon | undefined {
  return SERMONS.find((s) => s.id === id);
}

export function getSermonBySlug(slug: string): Sermon | undefined {
  return SERMONS.find((s) => s.slug === slug);
}

export function getSermonsByPastor(pastorId: string): Sermon[] {
  return SERMONS.filter((s) => s.pastorId === pastorId);
}

export function getTrending(limit = 6): Sermon[] {
  return [...SERMONS]
    .sort((a, b) => b.viewsThisWeek - a.viewsThisWeek)
    .slice(0, limit);
}

export function getRecent(limit = 6): Sermon[] {
  return [...SERMONS]
    .sort(
      (a, b) =>
        new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
    )
    .slice(0, limit);
}

export function getRelated(sermon: Sermon, limit = 4): Sermon[] {
  return SERMONS.filter((s) => s.id !== sermon.id)
    .map((s) => {
      let score = 0;
      if (s.pastorId === sermon.pastorId) score += 3;
      if (s.topic === sermon.topic) score += 2;
      score += s.tags.filter((t) => sermon.tags.includes(t)).length;
      return { s, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.s);
}
